# Generated by Django 5.0.6 on 2024-05-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallery",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="gallery",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
