# Generated by Django 5.0.6 on 2024-05-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_gallery_slug_gallery_views"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gallery",
            name="image",
        ),
        migrations.AddField(
            model_name="gallery",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="static/images/"),
        ),
    ]
