# Generated by Django 5.0.6 on 2024-05-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0003_remove_gallery_image_gallery_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery",
            name="cover",
            field=models.ImageField(default=2, upload_to="static/images/"),
            preserve_default=False,
        ),
    ]
