# Generated by Django 5.0.6 on 2024-05-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0004_alter_gallery_cover"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="static/images/")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="gallery",
            name="images",
            field=models.ManyToManyField(related_name="gallery", to="gallery.image"),
        ),
    ]
